type: map
mapping:
  :requests:
    required: yes
    type: map
    mapping:
      =:
        type: map
        mapping:
          :method:
            type: str
            enum: [GET, POST, DELETE, PUT]
          :path:
            type: str
          :parameters:
            type: map
            mapping:
              =:
                type: any
          :headers:
            type: map
            mapping:
              =:
                type: str
          :json:
            type: map
            mapping:
              =:
                type: any
          :oauth:
            type: map
            mapping:
              =:
                type: str
          :imports:
            type: seq
            sequence:
              - type: map
                mapping:
                  =:
                    type: any
  :responses:
    required: yes
    type: map
    mapping:
      =:
        type: map
        mapping:
          :status:
            type: int
          :condition:
            type: str
          :body:
            type: any
          :headers:
            type: map
            mapping:
              =:
                type: str
          :json:
            type: any
          :imports:
            type: seq
            sequence:
              - type: map
                mapping:
                  =:
                    type: any
          :transitions:
            type: map
            mapping:
              =:
                type: str
          :oauth:
            type: map
            mapping:
              =:
                type: str